import { Serie } from "./serie.js";

export const dataSeries = [
    new Serie("Chainsaw Man", "MAPPA", 1, "Denji es un joven pobre que trabaja como cazador de demonios para pagar las deudas que su difunto padre dejó atrás. Después de ser traicionado y asesinado por un grupo de yakuza, Denji hace un pacto con su mascota demonio motosierra, Pochita, y renace como el híbrido humano-demonio conocido como Chainsaw Man.", "./img/chainsawman.jpg", "https://www.crunchyroll.com/es/series/GVDHX8QNW/chainsaw-man"),
    new Serie("Attack on Titan", "Wit Studio / MAPPA", 4, "En un mundo donde la humanidad está al borde de la extinción debido a gigantes devoradores de hombres conocidos como titanes, Eren Yeager y sus amigos Mikasa Ackerman y Armin Arlert se unen al ejército para luchar contra estas criaturas y descubrir los secretos detrás de su existencia.", "./img/poster-attack-on-titan.jpg", "https://www.crunchyroll.com/es/series/GR751KNZY/attack-on-titan"),
    new Serie("Demon Slayer", "Ufotable", 3, "Tanjiro Kamado es un joven que se convierte en cazador de demonios para salvar a su hermana Nezuko, quien ha sido transformada en un demonio. Juntos, luchan contra poderosos demonios mientras buscan una cura para su hermana.", "./img/demonsalyer.jpg", "https://www.crunchyroll.com/es/series/GY5P48XEY/demon-slayer-kimetsu-no-yaiba"),
    new Serie("Jujutsu Kaisen", "MAPPA", 2, "Yuji Itadori, un estudiante de secundaria, se une a una organización secreta de hechiceros para combatir maldiciones después de consumir un objeto maldito. Junto a sus compañeros, lucha contra poderosos enemigos mientras busca una forma de salvar a sus amigos.", "./img/jjk2.jpg", "https://www.crunchyroll.com/es/series/GRDV0019R/jujutsu-kaisen"),
    new Serie("My Hero Academia", "Bones", 6, "En un mundo donde la mayoría de las personas tiene superpoderes, Izuku Midoriya, un chico sin poderes, sueña con convertirse en un héroe. Después de un encuentro con su ídolo, All Might, recibe la oportunidad de asistir a una prestigiosa escuela de héroes.", "./img/myheroac.jpg", "https://www.crunchyroll.com/es/series/G6NQ5DWZ6/my-hero-academia"),
    new Serie("To Be Hero X", "Bilibili / Aniplex", 1, "Este es un mundo en el que los mejores héroes son aclamados. El \"Valor de Confianza\" es lo que crea superhéroes. Si la gente cree que un héroe \"puede volar\", adquirirá la capacidad de volar. También ocurre al revés: aunque un héroe tenga poderes, si baja su Valor de Confianza, también perderá sus poderes. El Valor de Confianza se mide en forma de datos y se usa para clasificar a los héroes. Una vez cada dos años, los mejores héroes se reúnen para competir en un torneo especial. El Valor de Confianza de los participantes en el torneo varía en función de su rendimiento en el mismo, actualizándose posteriormente la clasificación, y al héroe que queda en lo más alto se lo conoce como \"X\"...", "./img/To_Be_Hero_X_key_art.png", "https://www.crunchyroll.com/es/series/GQWH0M1J3/to-be-hero-x")
]